#!/bin/bash

# This is too hard, I give up, for now.
# I want to be able to continuously put in commands
# 
# However this is hard, one way to do it I realized.
# is to record the time the normal recording starts
# then record the time the sound profiled one starts
# and then simply trim that time from the normal one

# How it will WORK
# 1 'follow' command
# 1 recording command.
# The recording command follows the 'follow' command, and ends when it ends,
# later it will trim what it trimed.

# Starts = Look for file size
# End = command ends.

# Possible good follow command
# rec speech.wav trim 0.2 noisered noise.prof 0.1 silence 1 0.1 1% 1 1.0 1%
#                      ^
#                      |
#         The trim removes an initial pop, they are common.

# Use date %s at the start and end then subtract
# to find out how much you need to trim the real audio file
