#!/usr/bin/python

import os
import subprocess

while True:
	if os.path.isfile("Microphone/pycmd_nocmd"):
		os.system("rec speech.flac silence 1 0.1 0.1% 1 0.5 0.1%")
		p = subprocess.Popen(['./send_speech', 'speech.flac'], stdout=subprocess.PIPE, 
                                       stderr=subprocess.PIPE)
		while(True):
			state = p.poll() #returns None while subprocess is running
			out = p.stdout.readline()
			if(state is not None):
				break
		print "Out:",out
		os.system("./recognize \""+str(out)+"\"")
