#!/bin/bash

# TODO
# Look for CONFIG file to see if it has SOUND or VISUAL set
# And display accordingly

if [ -e "speech.pid" ];then
    read PID_OF_SPEECH < speech.pid
    sleep .1 # This is so the end of the speech doesn't get cut off.
    kill $PID_OF_SPEECH

    ./pycmd wait
    while kill -s 0 $PID_OF_SPEECH 2>/dev/null;do
    :
    done
    RESULT="$(./send_speech speech.flac)"
    ./recognize "$RESULT"

    # Only takes effect if a script did not use pycmd result
    if [ ! -e "Microphone/result" ];then
	./pycmd done
    fi

    rm speech.pid
else
    ./pycmd stop
    > speech.flac
    rec -r 16000 -q -b 16 speech.flac 2>/dev/null & 
    echo $! > "speech.pid"
    # Checks when recording starts
    while [ "$(stat -c%s speech.flac)" == "0" ];do
    	:
    done
    ./pycmd record
fi
