#!/bin/bash

# Setup speech recognition for the person.

gksu -u root "apt-get install sox python-argparse wget espeak xautomation xvkbd -y"

DIR="$(pwd)"

echo Assuming all files are in "'$DIR'"

touch Recognition/dictionary.c
cd Recognition
make
cd ..
mkdir $HOME/.palaver.d/
cp Recognition/config/BlankInfo $HOME/.palaver.d/UserInfo
./installDefault
echo "Done, you will have to setup the hotkey yourself."
