#!/bin/bash

# Setup speech recognition for the person.

DIR="$(pwd)"

echo Assuming all files are in "'$DIR'"

touch Recognition/dictionary.c
cd Recognition
make
cd ..
mkdir $HOME/.pavaler.d/
cp Recognition/config/BlankInfo $HOME/.pavaler.d/UserInfo
nano $HOME/.pavaler.d/UserInfo

echo "Done, you will have to setup the hotkey yourself."



