#!/bin/bash

# Setup speech recognition for the person.

if [ "$(whoami)" != "root" ]; then
	echo "Sorry, Please run as root."
	exit 1
fi

sudo apt-get install sox python-argparse wget espeak xautomation xvkbd -y

DIR="$(pwd)"

echo Assuming all files are in "'$DIR'"

touch Recognition/dictionary.c
cd Recognition
make
cd ..
mkdir $HOME/.pavaler.d/
cp Recognition/config/BlankInfo $HOME/.pavaler.d/UserInfo
nano $HOME/.pavaler.d/UserInfo

echo "Done, you will have to setup the hotkey yourself."



